### Simple Hello

GET http://localhost:8080

### Simple Path Variable

GET http://localhost:8080/1


### Two Path Variables

GET http://localhost:8080/1/2

### Simple Hello

GET http://localhost:8080/user


### Request Param

GET http://localhost:8080/requestParams/?name=Vijay&email=vijaygenius123@gmail.com


### Add Employee V1

POST http://localhost:8080/employees/v1
Content-Type: application/json

{
  "firstName": "Vijay",
  "lastName": "S",
  "department": "Engineering",
  "emailId": "vijaygenius123@gmail.com"
}

### Get All Employees

GET http://localhost:8080/employees/v1?mediaType=xml


### Get Employee By ID

GET http://localhost:8080/employees/v1/58f6a114-b121-4334-80ad-9eaa069121ec

### Delete Employee By ID

DELETE http://localhost:8080/employees/v1/58f6a114-b121-4334-80ad-9eaa069121ec



### Add Employee V2

POST http://localhost:8080/employees/v2
Content-Type: application/json

{
  "firstName": "Jarvis",
  "lastName": "Doggy",
  "department": "Pets",
  "emailId": "jarvis@dogs.com"
}

### Get All Employees V2

GET http://localhost:8080/employees/v2


### Get Employee By ID V2

GET http://localhost:8080/employees/v2/70d4266a-6cc7-464e-9879-76eee618b057

### Delete Employee By ID

DELETE http://localhost:8080/employees/v2/fbddb913-e671-4c1e-891b-821457082ac7